server:
  port: 8088

spring:
  application:
    name: user-service
  datasource:
    url:  jdbc:mysql://localhost:3306/test
    username:  root
    password:  w123s
  redis:
    host:  192.168.178.134

  rabbitmq:
    host:  192.168.178.134
    username:  leyou
    password:  leyou
    virtual-host:  /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package:  com.wangshuai.bean
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
