server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address:  127.0.0.1
spring:
  application:
    name: Item-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: w123s

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
