server:
  port: 8082

spring:
  application:
    name: brand-service
  datasource:
    url: jdbc:mysql://localhost:3306/ly
    username: root
    password: w123s
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
